// Data behind the programmatic career guides (/career/:slug). Each entry powers
// one SEO page targeting "<role> salary / how to become / remote jobs / certs".
// Keep entries specific and truthful - quality pages, not thin spam.
export const CAREERS = [
  {
    slug: "cloud-engineer",
    role: "Cloud Engineer",
    category: "Cloud",
    salaryLow: 105000, salaryHigh: 160000,
    summary: "Cloud engineers design, build, and maintain the infrastructure that runs applications on AWS, Azure, or Google Cloud. It's one of the most in-demand and fully-remote-friendly roles in tech.",
    skills: ["AWS / Azure / GCP", "Infrastructure as Code (Terraform)", "Linux", "Networking", "CI/CD pipelines", "Docker & Kubernetes", "Python or Bash", "Monitoring & cost optimization"],
    certs: ["AWS Solutions Architect Associate", "Microsoft Azure Administrator (AZ-104)", "Google Associate Cloud Engineer", "HashiCorp Terraform Associate"],
    howTo: ["Build a Linux + networking foundation", "Learn one cloud deeply (AWS is the most-hired)", "Get a cloud certification to pass resume filters", "Build 2-3 hands-on projects (a deployed app, IaC repo)", "Apply to remote cloud and DevOps roles"],
    pathFrom: ["IT Support Specialist", "System Administrator"], pathTo: ["Cloud Architect", "DevOps Engineer"],
    faqs: [
      { q: "How much does a remote cloud engineer make?", a: "In the US and Canada, remote cloud engineers typically earn $105,000-$160,000 base, with senior and architect roles going higher." },
      { q: "How do I become a cloud engineer with no experience?", a: "Most people start in IT support or sysadmin work, learn one cloud platform (AWS is the most in demand), earn an associate-level certification, and build a few hands-on projects before applying." },
      { q: "Which cloud certification is best to start?", a: "The AWS Solutions Architect Associate opens the most doors. Azure Administrator (AZ-104) is best if you're targeting Microsoft-heavy employers." },
      { q: "Are cloud engineer jobs remote?", a: "Yes - cloud work is among the most remote-friendly roles in tech, with many fully remote positions across the US and Canada." },
    ],
  },
  {
    slug: "devops-engineer",
    role: "DevOps Engineer",
    category: "Cloud",
    salaryLow: 110000, salaryHigh: 170000,
    summary: "DevOps engineers automate how software is built, tested, and shipped, bridging development and operations with CI/CD pipelines, infrastructure as code, and cloud platforms.",
    skills: ["CI/CD (GitHub Actions, GitLab, Jenkins)", "Kubernetes & Docker", "Terraform / Ansible", "AWS / Azure / GCP", "Scripting (Python, Bash, Go)", "Observability (Prometheus, Grafana)", "Git", "Linux"],
    certs: ["AWS Certified DevOps Engineer", "Certified Kubernetes Administrator (CKA)", "HashiCorp Terraform Associate", "Azure DevOps Engineer Expert"],
    howTo: ["Master Linux, Git, and one scripting language", "Learn a cloud platform and containerization (Docker, Kubernetes)", "Build a CI/CD pipeline end to end", "Earn a DevOps or Kubernetes certification", "Showcase pipelines and IaC on GitHub, then apply"],
    pathFrom: ["System Administrator", "Cloud Engineer"], pathTo: ["Site Reliability Engineer", "Platform Engineer"],
    faqs: [
      { q: "What is a DevOps engineer's salary?", a: "Remote DevOps engineers in the US and Canada typically earn $110,000-$170,000, among the higher-paid infrastructure roles." },
      { q: "Is DevOps hard to get into?", a: "It's an intermediate role - most DevOps engineers come from sysadmin, cloud, or development backgrounds. Strong Linux, scripting, and CI/CD skills are the fastest way in." },
      { q: "Do I need to code for DevOps?", a: "Yes, scripting (Python, Bash, or Go) is essential for automation, though it's less about building features and more about tooling and pipelines." },
      { q: "Are DevOps jobs remote?", a: "Very much so - DevOps is one of the most remote-friendly roles, with abundant fully remote openings across North America." },
    ],
  },
  {
    slug: "it-support-specialist",
    role: "IT Support Specialist",
    category: "IT",
    salaryLow: 45000, salaryHigh: 70000,
    summary: "IT support specialists keep an organization's hardware, software, and users running smoothly. It's the most common entry point into tech and a launchpad into cloud, security, and systems roles.",
    skills: ["Troubleshooting", "Windows & macOS", "Active Directory", "Ticketing systems", "Basic networking", "Customer service", "Help desk tools", "Remote support"],
    certs: ["CompTIA A+", "CompTIA Network+", "Google IT Support Certificate", "Microsoft 365 Fundamentals"],
    howTo: ["Earn CompTIA A+ to validate fundamentals", "Learn Windows, Active Directory, and basic networking", "Practice troubleshooting and ticket workflows", "Apply to help desk and IT support roles", "Use the role to specialize into cloud, security, or sysadmin"],
    pathFrom: ["Career changer", "Recent grad"], pathTo: ["System Administrator", "Cloud Engineer"],
    faqs: [
      { q: "How much does IT support pay?", a: "Entry-level IT support roles in the US and Canada typically pay $45,000-$70,000, with remote help desk positions widely available." },
      { q: "How do I get an IT support job with no experience?", a: "Earn CompTIA A+ (or the Google IT Support Certificate), learn Windows and basic networking, and apply to help desk roles - many are entry-level and remote." },
      { q: "Is IT support a good career start?", a: "Yes - it's the most common on-ramp into tech and leads naturally into sysadmin, cloud, and cybersecurity roles." },
      { q: "Can IT support be done remotely?", a: "Many help desk and IT support roles are fully remote, handling tickets and remote troubleshooting from anywhere." },
    ],
  },
  {
    slug: "system-administrator",
    role: "System Administrator",
    category: "IT",
    salaryLow: 65000, salaryHigh: 100000,
    summary: "System administrators manage servers, networks, and IT infrastructure that keep a company running. The role is a strong bridge from IT support into cloud and DevOps.",
    skills: ["Windows Server & Linux", "Active Directory", "Networking", "Virtualization (VMware, Hyper-V)", "Scripting (PowerShell, Bash)", "Backup & recovery", "Patch management", "Cloud basics"],
    certs: ["CompTIA Server+", "Microsoft Certified: Windows Server", "Red Hat Certified System Administrator (RHCSA)", "CompTIA Network+"],
    howTo: ["Build on IT support fundamentals", "Learn Windows Server and Linux administration", "Pick up scripting (PowerShell or Bash)", "Earn a sysadmin certification", "Add cloud skills to move toward cloud/DevOps roles"],
    pathFrom: ["IT Support Specialist"], pathTo: ["Cloud Engineer", "DevOps Engineer"],
    faqs: [
      { q: "What does a system administrator earn?", a: "Remote system administrators in the US and Canada typically earn $65,000-$100,000 depending on experience and stack." },
      { q: "How do I become a system administrator?", a: "Most sysadmins start in IT support, then learn Windows Server, Linux, and scripting, and earn a certification like RHCSA or a Microsoft Server credential." },
      { q: "Is sysadmin a dying career?", a: "It's evolving - pure on-prem work is shrinking, but sysadmins who add cloud and automation skills are in strong demand and well-positioned for cloud/DevOps roles." },
      { q: "Are sysadmin jobs remote?", a: "Many are, especially in cloud-first organizations where infrastructure is managed remotely." },
    ],
  },
  {
    slug: "cybersecurity-analyst",
    role: "Cybersecurity Analyst",
    category: "Security",
    salaryLow: 85000, salaryHigh: 130000,
    summary: "Cybersecurity analysts protect organizations from threats by monitoring systems, investigating incidents, and hardening defenses. Demand far outstrips supply, and many roles are remote.",
    skills: ["SIEM tools (Splunk, Sentinel)", "Network security", "Incident response", "Vulnerability management", "Threat detection", "Scripting (Python)", "Cloud security basics", "Risk frameworks"],
    certs: ["CompTIA Security+", "CompTIA CySA+", "Certified Ethical Hacker (CEH)", "ISC2 Certified in Cybersecurity"],
    howTo: ["Build IT and networking fundamentals", "Earn CompTIA Security+ to enter the field", "Learn a SIEM and practice on home labs / CTFs", "Target SOC analyst roles to start", "Specialize (cloud security, incident response, GRC)"],
    pathFrom: ["IT Support Specialist", "Network Engineer"], pathTo: ["Cloud Security Engineer", "Security Engineer"],
    faqs: [
      { q: "How much do cybersecurity analysts make?", a: "Remote cybersecurity analysts in the US and Canada typically earn $85,000-$130,000, with strong growth as you specialize." },
      { q: "How do I get into cybersecurity?", a: "Start with IT and networking fundamentals, earn CompTIA Security+, practice with home labs and capture-the-flag exercises, then target SOC analyst roles." },
      { q: "Do cybersecurity jobs require a degree?", a: "Not always - certifications, hands-on labs, and demonstrable skills often matter more than a degree, especially for analyst roles." },
      { q: "Is cybersecurity remote-friendly?", a: "Yes, many SOC and analyst roles are fully remote, monitoring and responding to threats from anywhere." },
    ],
  },
  {
    slug: "cloud-architect",
    role: "Cloud Architect",
    category: "Cloud",
    salaryLow: 140000, salaryHigh: 210000,
    summary: "Cloud architects design the high-level cloud strategy and systems for an organization, balancing performance, security, and cost. It's a senior, highly-paid, remote-friendly role.",
    skills: ["Cloud architecture (AWS/Azure/GCP)", "Networking & security design", "Infrastructure as Code", "Cost optimization", "Microservices", "Stakeholder communication", "Multi-cloud / hybrid", "Compliance"],
    certs: ["AWS Solutions Architect Professional", "Azure Solutions Architect Expert", "Google Professional Cloud Architect", "TOGAF"],
    howTo: ["Gain several years as a cloud or DevOps engineer", "Master architecture, security, and cost design", "Earn a professional-level cloud architecture cert", "Lead a cloud migration or major design", "Move into architect roles"],
    pathFrom: ["Cloud Engineer", "DevOps Engineer"], pathTo: ["Principal Architect", "Engineering Manager"],
    faqs: [
      { q: "What is a cloud architect's salary?", a: "Remote cloud architects in the US and Canada typically earn $140,000-$210,000+, making it one of the highest-paid cloud roles." },
      { q: "How long does it take to become a cloud architect?", a: "Usually several years - most architects first spend time as cloud or DevOps engineers before moving into design-focused architect roles." },
      { q: "Which certification do cloud architects need?", a: "Professional-level certs like AWS Solutions Architect Professional or Azure Solutions Architect Expert are the standard." },
      { q: "Is cloud architecture a remote job?", a: "Yes, it's highly remote-friendly, as the work is design, strategy, and collaboration rather than physical infrastructure." },
    ],
  },
  {
    slug: "epic-analyst",
    role: "Epic / EHR Analyst",
    category: "Healthcare IT",
    salaryLow: 70000, salaryHigh: 110000,
    summary: "Epic and EHR analysts configure and support electronic health record systems that hospitals and clinics run on. It blends healthcare and IT, and many roles are remote.",
    skills: ["Epic or Cerner systems", "EHR configuration", "Healthcare workflows", "HL7 / interoperability basics", "SQL / reporting", "Troubleshooting", "HIPAA awareness", "Stakeholder training"],
    certs: ["Epic certification (employer-sponsored)", "CAHIMS", "CompTIA Healthcare IT Technician", "Certified Healthcare Technology Specialist (CHTS)"],
    howTo: ["Build healthcare or IT experience", "Get into a role that sponsors Epic certification", "Earn Epic certification in a module (e.g., EpicCare)", "Learn reporting and interoperability", "Target remote EHR analyst roles"],
    pathFrom: ["Healthcare worker", "IT Support Specialist"], pathTo: ["Clinical Informatics Specialist", "Healthcare IT Project Manager"],
    faqs: [
      { q: "How much do Epic analysts make?", a: "Remote Epic/EHR analysts in the US and Canada typically earn $70,000-$110,000, with certified analysts in strong demand." },
      { q: "How do I become an Epic analyst?", a: "Epic certification is usually employer-sponsored, so the path is getting into a healthcare IT role that sponsors you, often from a clinical or IT support background." },
      { q: "Do I need clinical experience to be an EHR analyst?", a: "It helps but isn't always required - both clinical staff moving into IT and IT professionals learning healthcare workflows succeed in the role." },
      { q: "Are Epic analyst jobs remote?", a: "Many are fully remote, configuring and supporting EHR systems for health systems across the country." },
    ],
  },
  {
    slug: "healthcare-data-analyst",
    role: "Healthcare Data Analyst",
    category: "Healthcare IT",
    salaryLow: 70000, salaryHigh: 105000,
    summary: "Healthcare data analysts turn clinical and operational data into insights that improve care and efficiency. It's a fast-growing, remote-friendly blend of data skills and healthcare knowledge.",
    skills: ["SQL", "Excel & BI tools (Tableau, Power BI)", "Healthcare data (claims, EHR)", "Statistics", "Data visualization", "HIPAA compliance", "Python or R (helpful)", "Reporting"],
    certs: ["Certified Health Data Analyst (CHDA)", "Tableau Desktop Specialist", "Microsoft Power BI Data Analyst", "Google Data Analytics Certificate"],
    howTo: ["Learn SQL and a BI tool well", "Understand healthcare data types and HIPAA", "Build a portfolio with healthcare datasets", "Earn a data analytics certificate", "Apply to remote healthcare analyst roles"],
    pathFrom: ["Data Analyst", "Healthcare worker"], pathTo: ["Clinical Informatics Specialist", "Data Scientist"],
    faqs: [
      { q: "What does a healthcare data analyst earn?", a: "Remote healthcare data analysts in the US and Canada typically earn $70,000-$105,000, with demand rising as healthcare digitizes." },
      { q: "How do I become a healthcare data analyst?", a: "Learn SQL and a BI tool like Tableau or Power BI, understand healthcare data and HIPAA, and build a small portfolio before applying." },
      { q: "Do I need a healthcare background?", a: "It helps, but strong data skills plus a willingness to learn healthcare workflows and compliance can be enough to break in." },
      { q: "Is this role remote?", a: "Yes, healthcare data analysis is largely remote-friendly since the work is data and reporting." },
    ],
  },
  {
    slug: "site-reliability-engineer",
    role: "Site Reliability Engineer",
    category: "Cloud",
    salaryLow: 125000, salaryHigh: 190000,
    summary: "Site reliability engineers (SREs) keep large-scale systems fast and reliable using automation, monitoring, and software engineering practices. It's a senior, high-paying, remote-friendly role.",
    skills: ["Kubernetes", "Cloud platforms", "Observability (Prometheus, Grafana)", "Programming (Go, Python)", "Incident management", "Terraform / IaC", "Distributed systems", "Automation"],
    certs: ["Certified Kubernetes Administrator (CKA)", "AWS DevOps Engineer Professional", "Google Professional Cloud DevOps Engineer", "Terraform Associate"],
    howTo: ["Build strong DevOps and cloud foundations", "Learn distributed systems and observability", "Strengthen programming (Go or Python)", "Earn Kubernetes or cloud DevOps certs", "Target SRE roles at scale-focused companies"],
    pathFrom: ["DevOps Engineer", "Software Engineer"], pathTo: ["Staff SRE", "Platform Engineering Lead"],
    faqs: [
      { q: "How much do SREs make?", a: "Remote site reliability engineers in the US and Canada typically earn $125,000-$190,000+, among the best-paid infrastructure roles." },
      { q: "What's the difference between DevOps and SRE?", a: "They overlap heavily; SRE applies software-engineering rigor to reliability (SLOs, error budgets), while DevOps focuses on delivery pipelines and culture." },
      { q: "How do I become an SRE?", a: "Most SREs come from DevOps or software engineering, then deepen their skills in distributed systems, observability, and automation." },
      { q: "Are SRE jobs remote?", a: "Yes, SRE is highly remote-friendly, especially at cloud-native companies." },
    ],
  },
  {
    slug: "network-engineer",
    role: "Network Engineer",
    category: "IT",
    salaryLow: 75000, salaryHigh: 120000,
    summary: "Network engineers design, build, and maintain the networks that connect an organization. The role increasingly blends traditional networking with cloud and automation.",
    skills: ["Routing & switching", "TCP/IP", "Firewalls & VPNs", "Cisco / Juniper", "Cloud networking", "Network automation (Python)", "Troubleshooting", "SD-WAN"],
    certs: ["Cisco CCNA", "CompTIA Network+", "Cisco CCNP", "AWS Advanced Networking"],
    howTo: ["Master networking fundamentals (TCP/IP, routing, switching)", "Earn CCNA", "Get hands-on with real or virtual labs", "Add cloud networking and automation", "Apply to network engineering roles"],
    pathFrom: ["IT Support Specialist"], pathTo: ["Cloud Engineer", "Network Architect"],
    faqs: [
      { q: "What is a network engineer's salary?", a: "Remote network engineers in the US and Canada typically earn $75,000-$120,000 depending on experience and certifications." },
      { q: "How do I become a network engineer?", a: "Learn networking fundamentals, earn a CCNA, practice in labs, and add cloud networking skills to stay current." },
      { q: "Is the CCNA worth it?", a: "Yes - the Cisco CCNA is one of the most respected entry credentials for networking roles and passes many resume filters." },
      { q: "Are network engineering jobs remote?", a: "Increasingly yes, especially roles focused on cloud and software-defined networking." },
    ],
  },
  {
    slug: "clinical-informatics-specialist",
    role: "Clinical Informatics Specialist",
    category: "Healthcare IT",
    salaryLow: 85000, salaryHigh: 125000,
    summary: "Clinical informatics specialists sit between clinicians and IT, improving how technology supports patient care. It's ideal for nurses and clinicians moving into health tech, and often remote.",
    skills: ["Clinical workflows", "EHR systems (Epic, Cerner)", "Data analysis", "Change management", "HL7 / interoperability", "Quality improvement", "HIPAA", "Stakeholder training"],
    certs: ["CPHIMS", "Epic certification", "Board Certification in Clinical Informatics", "CAHIMS"],
    howTo: ["Build clinical experience (often nursing)", "Learn EHR systems and informatics concepts", "Earn CAHIMS or CPHIMS", "Lead an informatics or EHR initiative", "Move into a clinical informatics role"],
    pathFrom: ["Nurse / Clinician", "Epic Analyst"], pathTo: ["Informatics Manager", "Chief Medical Information Officer track"],
    faqs: [
      { q: "What does a clinical informatics specialist earn?", a: "Remote clinical informatics specialists in the US and Canada typically earn $85,000-$125,000, with nursing-informatics backgrounds in high demand." },
      { q: "How do I move from nursing into informatics?", a: "Leverage your clinical experience, learn EHR systems and informatics concepts, earn CAHIMS or CPHIMS, and get involved in EHR or quality projects." },
      { q: "Do I need to be a nurse?", a: "Not always, but a clinical background is a major advantage; the role is about translating between clinicians and technology." },
      { q: "Is clinical informatics remote?", a: "Many roles are remote or hybrid, focused on analysis, optimization, and stakeholder collaboration." },
    ],
  },
  {
    slug: "help-desk-technician",
    role: "Help Desk Technician",
    category: "IT",
    salaryLow: 40000, salaryHigh: 60000,
    summary: "Help desk technicians are the first line of IT support, resolving user issues and learning the fundamentals that lead to nearly every other tech career. It's the classic entry point.",
    skills: ["Troubleshooting", "Windows & Office 365", "Ticketing systems", "Customer service", "Basic networking", "Remote support tools", "Password / account management", "Documentation"],
    certs: ["CompTIA A+", "Google IT Support Certificate", "Microsoft 365 Fundamentals", "ITIL Foundation"],
    howTo: ["Earn the Google IT Support Certificate or CompTIA A+", "Practice troubleshooting common issues", "Learn ticketing and remote-support tools", "Apply to remote help desk roles", "Use it to step into sysadmin, cloud, or security"],
    pathFrom: ["Career changer", "Recent grad"], pathTo: ["IT Support Specialist", "System Administrator"],
    faqs: [
      { q: "How much does a help desk technician make?", a: "Entry-level help desk roles in the US and Canada typically pay $40,000-$60,000, and many are remote." },
      { q: "How do I get a help desk job with no experience?", a: "Earn the Google IT Support Certificate or CompTIA A+, practice troubleshooting, and apply broadly - help desk is designed for entry-level candidates." },
      { q: "Is help desk a good first tech job?", a: "Yes - it teaches the fundamentals that lead into almost every other IT, cloud, and security career." },
      { q: "Can help desk be remote?", a: "Many help desk roles are fully remote, handling tickets and remote troubleshooting." },
    ],
  },
];

export const careerBySlug = (slug) => CAREERS.find((c) => c.slug === slug) || null;
